BEGIN;

CREATE TABLE IF NOT EXISTS categoria (
    categoria_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(80) NOT NULL,
    descricao       VARCHAR(255),
    CONSTRAINT pk_categoria PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categoria_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS produto (
    produto_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_id    BIGINT NOT NULL,
    nome            VARCHAR(120) NOT NULL,
    descricao       VARCHAR(255),
    preco           NUMERIC(10,2) NOT NULL CHECK (preco > 0),
    ativo           BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT pk_produto PRIMARY KEY (produto_id),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id)
        REFERENCES categoria (categoria_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_produto_nome UNIQUE (nome)
);

CREATE INDEX IF NOT EXISTS idx_produto_categoria_id ON produto(categoria_id);
CREATE INDEX IF NOT EXISTS idx_produto_nome ON produto(nome);

CREATE TABLE IF NOT EXISTS cliente (
    cliente_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(120) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    telefone        VARCHAR(20),
    logradouro      VARCHAR(150),
    numero          VARCHAR(20),
    complemento     VARCHAR(50),
    bairro          VARCHAR(80),
    cidade          VARCHAR(80),
    uf              CHAR(2),
    cep             VARCHAR(12),
    criado_em       TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
    CONSTRAINT uq_cliente_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS pedido (
    pedido_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id      BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL,
    aberto_em       TIMESTAMP NOT NULL DEFAULT now(),
    atualizado_em   TIMESTAMP NOT NULL DEFAULT now(),
    observacoes     VARCHAR(255),
    CONSTRAINT pk_pedido PRIMARY KEY (pedido_id),
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente (cliente_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_pedido_status CHECK (status IN ('ABERTO','PAGO','EM_ENTREGA','ENTREGUE','CANCELADO'))
);

CREATE INDEX IF NOT EXISTS idx_pedido_cliente_id ON pedido(cliente_id);
CREATE INDEX IF NOT EXISTS idx_pedido_status ON pedido(status);

CREATE TABLE IF NOT EXISTS item_pedido (
    item_pedido_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id       BIGINT NOT NULL,
    produto_id      BIGINT NOT NULL,
    quantidade      INTEGER NOT NULL,
    preco_unitario  NUMERIC(10,2) NOT NULL,
    total           NUMERIC(12,2) GENERATED ALWAYS AS (quantidade * preco_unitario) STORED,
    CONSTRAINT pk_item_pedido PRIMARY KEY (item_pedido_id),
    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedido (pedido_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_item_pedido_produto FOREIGN KEY (produto_id)
        REFERENCES produto (produto_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_item_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_item_preco CHECK (preco_unitario > 0)
);

CREATE INDEX IF NOT EXISTS idx_item_pedido_pedido_id ON item_pedido(pedido_id);
CREATE INDEX IF NOT EXISTS idx_item_pedido_produto_id ON item_pedido(produto_id);

CREATE TABLE IF NOT EXISTS estoque (
    produto_id      BIGINT PRIMARY KEY,
    quantidade      INTEGER NOT NULL DEFAULT 0,
    atualizado_em   TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id)
        REFERENCES produto (produto_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade >= 0)
);

CREATE TABLE IF NOT EXISTS auditoria_estoque (
    auditoria_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id      BIGINT NOT NULL,
    quantidade      INTEGER NOT NULL, 
    motivo          VARCHAR(120) NOT NULL,
    criado_em       TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT pk_auditoria_estoque PRIMARY KEY (auditoria_id),
    CONSTRAINT fk_auditoria_produto FOREIGN KEY (produto_id)
        REFERENCES produto (produto_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auditoria_produto_id ON auditoria_estoque(produto_id);

CREATE TABLE IF NOT EXISTS pagamento (
    pagamento_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id       BIGINT NOT NULL,
    valor           NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    metodo          VARCHAR(30) NOT NULL, 
    status          VARCHAR(20) NOT NULL,
    criado_em       TIMESTAMP NOT NULL DEFAULT now(),
    atualizado_em   TIMESTAMP NOT NULL DEFAULT now(),
    transacao_ref   VARCHAR(80),
    CONSTRAINT pk_pagamento PRIMARY KEY (pagamento_id),
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedido (pedido_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_pagamento_status CHECK (status IN ('PENDENTE','APROVADO','RECUSADO'))
);

CREATE INDEX IF NOT EXISTS idx_pagamento_pedido_id ON pagamento(pedido_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pagamento_aprovado_por_pedido
    ON pagamento(pedido_id)
    WHERE (status = 'APROVADO');

CREATE TABLE IF NOT EXISTS entrega (
    entrega_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pedido_id       BIGINT NOT NULL UNIQUE,
    status          VARCHAR(20) NOT NULL,
    previsao        TIMESTAMP,
    retirado_em     TIMESTAMP,     
    enviado_em      TIMESTAMP,
    entregue_em     TIMESTAMP,
    endereco        VARCHAR(200),  
    CONSTRAINT pk_entrega PRIMARY KEY (entrega_id),
    CONSTRAINT fk_entrega_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedido (pedido_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_entrega_status CHECK (status IN ('PENDENTE','EM_ROTA','ENTREGUE','CANCELADA'))
);

CREATE INDEX IF NOT EXISTS idx_entrega_status ON entrega(status);

CREATE VIEW vw_pedidos_resumo AS
SELECT
    p.pedido_id,
    c.nome        AS cliente_nome,
    c.cidade      AS cliente_cidade,
    p.status      AS pedido_status,
    COALESCE(SUM(i.total),0) AS total_itens,
    (SELECT pa.status
     FROM pagamento pa
     WHERE pa.pedido_id = p.pedido_id
     ORDER BY pa.criado_em DESC
     LIMIT 1) AS pagamento_status,
    e.status      AS entrega_status,
    p.aberto_em,
    p.atualizado_em
FROM pedido p
JOIN cliente c ON c.cliente_id = p.cliente_id
LEFT JOIN item_pedido i ON i.pedido_id = p.pedido_id
LEFT JOIN entrega e ON e.pedido_id = p.pedido_id
GROUP BY p.pedido_id, c.nome, c.cidade, p.status, e.status, p.aberto_em, p.atualizado_em;

COMMIT;
